services:
  #region development services
  driveplan_backend_dev:
    container_name: driveplan_backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    env_file: ./backend/.env.local
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    profiles: ["dev"]
    restart: unless-stopped

  driveplan_nginx_dev:
    container_name: driveplan_nginx_dev
    build:
      context: .
      dockerfile: nginx_dev/Dockerfile
    ports:
      - "4000:80"  # Development port
    depends_on:
      - driveplan_backend_dev
    profiles: ["dev"]
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For Ubuntu compatibility
    volumes:
      - ./nginx_dev/nginx.conf:/etc/nginx/nginx.conf
  #endregion

  #region production services
  driveplan_backend:
    container_name: driveplan_backend
    image: ghcr.io/allania7med11/driveplan_backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    env_file: ./backend/.env.production.local
    environment:
      - ENVIRONMENT=prod
      - DEBUG=False
      - MIGRATE=true
      - PORT=8000
    profiles: ["prod"]

  driveplan_nginx:
    container_name: driveplan_nginx
    image: ghcr.io/allania7med11/driveplan_nginx:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "4010:80"  # Local production testing port
    depends_on:
      - driveplan_backend
    profiles: ["prod"]
    env_file: ./nginx/.env.production.local
  #endregion